/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesCustomizeChromeNewTabRouteImport } from './routes/guides.customize-chrome-new-tab'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesCustomizeChromeNewTabRoute =
  GuidesCustomizeChromeNewTabRouteImport.update({
    id: '/guides/customize-chrome-new-tab',
    path: '/guides/customize-chrome-new-tab',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/customize-chrome-new-tab': typeof GuidesCustomizeChromeNewTabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/customize-chrome-new-tab': typeof GuidesCustomizeChromeNewTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/customize-chrome-new-tab': typeof GuidesCustomizeChromeNewTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/guides/customize-chrome-new-tab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/guides/customize-chrome-new-tab'
  id: '__root__' | '/' | '/sitemap.xml' | '/guides/customize-chrome-new-tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuidesCustomizeChromeNewTabRoute: typeof GuidesCustomizeChromeNewTabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/customize-chrome-new-tab': {
      id: '/guides/customize-chrome-new-tab'
      path: '/guides/customize-chrome-new-tab'
      fullPath: '/guides/customize-chrome-new-tab'
      preLoaderRoute: typeof GuidesCustomizeChromeNewTabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuidesCustomizeChromeNewTabRoute: GuidesCustomizeChromeNewTabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
